# Generated by Django 4.2.16 on 2024-10-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='from_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_from', to='database.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='to_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_to', to='database.profile'),
        ),
    ]
